from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from battery_estimation.data.synthetic import simulate_dataset
from battery_estimation.evaluation import calculate_metrics
from battery_estimation.health import (
    pulse_anchored_fresh_parameters,
    run_kalman_observers,
)


def main() -> None:
    health = json.loads((ROOT / "results/metrics/cx2_pulse_aging.json").read_text(encoding="utf-8"))
    measured, checkpoint = health["measured_health"], health["observer_checkpoint"]
    fresh = pulse_anchored_fresh_parameters(measured["initial_capacity_ah"], measured["initial_5s_pulse_resistance_ohm"])
    true_aged = fresh.aged(checkpoint["true_capacity_factor"], checkpoint["true_resistance_factor"])
    candidates = {
        "fresh_fixed": fresh,
        "aged_fixed_oracle": true_aged,
        "estimated_aging_aware": fresh.aged(checkpoint["estimated_capacity_factor"], checkpoint["estimated_resistance_factor"]),
    }
    dt_s, noise_v = 1.0, 0.005
    dataset = simulate_dataset(true_aged, dt_s, 3600.0, 0.90, noise_v, 0.015, 0.0, 124, checkpoint["true_resistance_factor"])
    all_estimates, metrics = {}, {}
    for parameter_case, params in candidates.items():
        estimates = run_kalman_observers(params, dt_s, dataset.current_a, dataset.voltage_v, 0.75, noise_v)
        all_estimates[parameter_case] = estimates
        metrics[parameter_case] = {}
        for observer, estimate in estimates.items():
            metric = calculate_metrics(dataset.true_soc, estimate, dt_s)
            metric["post_300s_rmse_pct"] = calculate_metrics(dataset.true_soc[300:], estimate[300:], dt_s)["rmse_pct"]
            metrics[parameter_case][observer] = metric
    output = {
        "validation_scope": "Semi-empirical: health factors are measured on CALCE CX2-3; dynamic SOC/voltage are generated by the 2-RC ECM.",
        "measured_checkpoint": checkpoint,
        "benchmark": metrics,
    }
    (ROOT / "results/metrics/aging_aware_comparison.json").write_text(json.dumps(output, indent=2), encoding="utf-8")
    fig, axes = plt.subplots(2, 1, figsize=(11, 8), sharex=True)
    axes[0].plot(dataset.time_s, dataset.current_a, lw=0.7)
    axes[0].set_ylabel("Current [A]")
    axes[0].grid(alpha=.25)
    axes[1].plot(dataset.time_s, 100 * dataset.true_soc, "k", lw=1.5, label="True aged model")
    styles = {"fresh_fixed": ":", "aged_fixed_oracle": "-.", "estimated_aging_aware": "--"}
    for case, estimates in all_estimates.items():
        axes[1].plot(dataset.time_s, 100 * estimates["ekf"], styles[case], lw=1.0, label=f"EKF: {case}")
    axes[1].set_ylabel("SOC [%]")
    axes[1].set_xlabel("Time [s]")
    axes[1].grid(alpha=.25)
    axes[1].legend(ncol=2)
    fig.suptitle("Measured-aging-informed SOC observer comparison")
    fig.tight_layout()
    fig.savefig(ROOT / "results/figures/aging_aware_comparison.png", dpi=160)
    plt.close(fig)
    lines = ["# Aging-aware SOC observer comparison", "", output["validation_scope"], "", "| Parameters | Observer | RMSE [%pt] | RMSE after 300 s [%pt] |", "|---|---:|---:|---:|"]
    for case, observers in metrics.items():
        for name, values in observers.items():
            lines.append(f"| {case} | {name.upper()} | {values['rmse_pct']:.3f} | {values['post_300s_rmse_pct']:.3f} |")
    (ROOT / "results/reports/aging_aware_comparison.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
